/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const PredictionHistory = IDL.Record({
  'applianceCount' : IDL.Nat,
  'predictedUnits' : IDL.Float64,
  'billTotal' : IDL.Float64,
  'householdType' : IDL.Text,
  'co2Emissions' : IDL.Float64,
  'timestamp' : Time,
  'dailyUsage' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addPrediction' : IDL.Func([PredictionHistory], [IDL.Nat], []),
  'getAllPredictions' : IDL.Func([], [IDL.Vec(PredictionHistory)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const PredictionHistory = IDL.Record({
    'applianceCount' : IDL.Nat,
    'predictedUnits' : IDL.Float64,
    'billTotal' : IDL.Float64,
    'householdType' : IDL.Text,
    'co2Emissions' : IDL.Float64,
    'timestamp' : Time,
    'dailyUsage' : IDL.Float64,
  });
  
  return IDL.Service({
    'addPrediction' : IDL.Func([PredictionHistory], [IDL.Nat], []),
    'getAllPredictions' : IDL.Func([], [IDL.Vec(PredictionHistory)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };